### ISSUE TITLE
期中報告

### ISSUE THREAD

**Issue by mdecourse** [mdecourse/wcms2018#10]
# 分組期中報告

請在期中考週上課之前, 各組分別在 Youtube 上傳一份簡報影片, 並在以下回報各組與各組員的期中報告內容與自評

**Comment by 40623121** [comment]
期中報告內容 : https://mde40623121.herokuapp.com
自評 : 60分

**Comment by 40623140** [comment]
第十四組期中簡報：https://xiran.herokuapp.com/edit_page
40623140 韓希然 期中影片 https://youtu.be/XPcEXO_xstw

**Comment by 40623120** [comment]
第十七組期中簡報 :http://wcms-40623120.herokuapp.com/get_page/%E4%B8%BB%E9%A0%81
自評:70分

**Comment by 40623102** [comment]
第12組期中簡報 : https://weiyun40623105.herokuapp.com
期中報告影片 : https://youtu.be/tX4EpmaHiic
自評 : 76分

**Comment by 40623147** [comment]
第12組期中簡報 : https://wcms-40623147.herokuapp.com
期中報告影片 : https://youtu.be/CXfKG2w0UMY
自評 : 77分

**Comment by 40623104** [comment]
第13組期中簡報:http://test40623104.herokuapp.com/get_page/%E7%B6%B2%E9%9A%9B%E7%B6%B2%E8%B7%AF%E7%AE%A1%E7%90%86
期中報告影片:https://www.youtube.com/watch?v=PuBS5yPruLg
自評:72

**Comment by 40623136** [comment]
第9組期中簡報 : https://hxs87.herokuapp.com
期中報告影片 : https://youtu.be/-Cq8EBtC5n4
自評 : 75分

**Comment by 40623116** [comment]
第4組期中報告內容 : https://bang669.herokuapp.com
期中報告影片 : https://youtu.be/28NmV07W6Uk
自評 : 76分

**Comment by 40623122** [comment]
第7組期中簡報 :https://tbz184.herokuapp.com/
自評 : 78分

**Comment by 40623109** [comment]
第1組期末簡報:https://wcms-40623109.herokuapp.com/get_page/%E7%B5%84%E5%93%A1
期中報告影片:https://www.youtube.com/watch?v=3TMtoBuPw1A&feature=youtu.be
自評:79分

**Comment by 40623150** [comment]
第3組期中簡報:https://han4062.herokuapp.com/get_page/Home
期中報告影片:https://youtu.be/CO0p36pCegU
自評:75

**Comment by 40623144** [comment]
第2組期中簡報:https://wcms-40623144.herokuapp.com
自評:66分

**Comment by 40623128** [comment]
第10組期中報告 : https://wcms-40623128.herokuapp.com
自評 : 85分
