### ISSUE TITLE
期末報告影片回報區

### ISSUE THREAD

**Issue by mdecourse** [mdecourse/wcms2018#12]
請各組組員在期末考週之前, 將 3-5 分鐘期末報告影片上傳到 Youtube 後, 在下列回報連結.

# 請在影片標題註明: 國立虎尾科技大學 - 機械設計工程系 - 網際內容管理 - 學號 期末報告

# 並在影片說明欄位附上個人倉儲連結, 以利評分.

**Comment by 40623128** [comment]
第一大組 第三小組
40623130網址:https://www.youtube.com/watch?v=WD4qbyOqjr4
40623129網址:
40623128網址:https://www.youtube.com/watch?v=TPZ3Pf5gh9Q

**Comment by 40623133** [comment]
第二大組 第二小組
40623133網址:https://www.youtube.com/watch?v=s3p-Hmqzc2E
40623111網址:https://www.youtube.com/watch?v=0ts-7_9pkwQ&feature=youtu.be
40623150網址:https://www.youtube.com/watch?v=5ne9wPdm9aw&feature=youtu.be

**Comment by 40623105** [comment]
第三大組 第三小組
40623105網址:https://youtu.be/P8NfsU1H11c

**Comment by 40623121** [comment]
第一大組 第四小組
40623121網址 : https://youtu.be/kZZTryyCuaU

**Comment by 40623140** [comment]
第二大組 第十四小組
網際內容管理 期末影片
40623140 網址：  https://youtu.be/2XAhAk0lbgg

**Comment by 40623116** [comment]
第一大組 第一小組
40623116 網址：https://youtu.be/q19-YfCANoo

**Comment by 40623135** [comment]
第一大組 第四小組
40623135 網址：https://youtu.be/odaj0avO6vM

**Comment by 40623104** [comment]
第三大組 第四小組
網際內容管理 期末影片
40623104 網址： https://www.youtube.com/watch?v=gMcqIRu8FSc

**Comment by 40623108** [comment]
第三大組 第四小組
網際內容管理 期末影片
40623108 網址： https://www.youtube.com/watch?v=e3AKNtIjR-Q&feature=youtu.be

**Comment by 40623109** [comment]
第二大組 第一小組
網際內容管理 期末影片
40623101 網址:https://www.youtube.com/watch?v=igyHihWjHTU&t=8s
40623109 網址:https://www.youtube.com/watch?v=b00ltlU3sKQ

**Comment by 40623103** [comment]
第三大組 第四小組
網際內容管理 期末影片
40623103網址:：https://youtu.be/92lsE8aqeGs

**Comment by 40623124** [comment]
第三大組第三小組
40623124：https://www.youtube.com/watch?v=-S1NHqYgwKc&feature=youtu.be

**Comment by 40623109** [comment]
第二大組 第一小組
網際內容管理 期末影片
40623101網址:：https://www.youtube.com/watch?v=igyHihWjHTU
40623107網址:：https://www.youtube.com/watch?v=KUws91suowI&feature=youtu.be
40623109網址:：https://www.youtube.com/watch?v=b00ltlU3sKQ

**Comment by 40623122** [comment]
第二大組 第三小組
40623122 網址 : https://youtu.be/vZnnSVDz4zU

**Comment by 40623110** [comment]
第一大組第一小組
40623110:https://www.youtube.com/watch?v=ZFSy3ftMoPk&feature=youtu.be

**Comment by 40623125** [comment]
第二大組第三小組
40623125 網址:https://www.youtube.com/watch?v=1qWa3NVg9pQ&feature=youtu.be

**Comment by 40623138** [comment]
第二大組第四小組
40623138 網址 : https://youtu.be/tfOUJOW5bYA

**Comment by 40623118** [comment]
第二大組 第三小組
40623118 網址 :https://youtu.be/N9IorWLy_nA

**Comment by 40623144** [comment]
第三大組第一小組
40623144 網址 : https://youtu.be/AdzUmR0nG4Y

**Comment by 40623141** [comment]
第二大組第四小組
40623141 網址 :https://youtu.be/4cLP5zREJwU

**Comment by 40623119** [comment]
第三大組第二小組
40623119 網址-：https://www.youtube.com/watch?v=TAtpuLmA53Y&t=4s

**Comment by 40623137** [comment]
第三大組第二小組
40623137 網址：https://youtu.be/ubDYydf7VQg

**Comment by 40623142** [comment]
第三大組第一小組
40623145 網址 : https://youtu.be/CvzJF5YjxRo

**Comment by 40623145** [comment]
第三大組第一小組
40623145 網址 : https://youtu.be/CvzJF5YjxRo

**Comment by 40623142** [comment]
第三大組第一小組
40623142 網址 :https://youtu.be/RyYkc8HwQDI

**Comment by 40623152** [comment]
第一大組 第四小組
40623152網址 :https://youtu.be/r5DQIdQQO7Q

**Comment by 40623120** [comment]
第二大組 第六小組
40623120網址:https://youtu.be/HDdG85Phtqg

**Comment by 40623117** [comment]
第一大組 第二小組
40623117網址:https://youtu.be/3uFUTNXtIlE

**Comment by 40623131** [comment]
第一大組 第二小組 
40623131 https://youtu.be/9diqrrXxUKw

**Comment by 40623127** [comment]
第一大組 第二小組
40623127 網站：https://youtu.be/_IBL9GAhIbc

**Comment by 40623113** [comment]
第一大組  第一小組
40623113網站:https://youtu.be/lSx4yGeWQlk

**Comment by 40623136** [comment]
第3大組-第2小組
40623136網站:https://www.youtube.com/watch?v=MgigZe8mkI4&t=1s
