### ISSUE TITLE
電腦教室系統安裝與管理

### ISSUE THREAD

**Issue by mdecourse** [mdecourse/wcms2018#7]
# 前言

## 電腦分布與統計

機械設計工程系目前共有八樓 60 台電腦教室兩間, 30 台電腦教室兩間, 分別位於七樓與九樓, 八樓工作站室伺服器 50 台, 以及其他分布在六至八樓研究生與專題用電腦約 100 台, 總共電腦總數超過 330 台, 目前的工作站伺服器約有 Windows serve 20 台, 其餘 Ubuntu server 30 台之外, 四間電腦教室中的 180 台電腦目前採用防寫卡, 以安裝 Windows 10 操作系統為主.

## 所面臨 Windows 10 更新問題

由於最新的 Windows 10 操作系統更新頻繁, 且利用 AI 擷取使用者習慣, 試圖在特定使用期間, 找出最適開機與使用模式下, 先前以防寫卡保護的電腦管理方式, 已經不符合實際需求, 因為目前四間電腦教室的 Windows 10 為兩年前的版本, 因此每次開機都重複下載更新套件, 在使用期間不斷進行更新後, 一旦關機後, 防寫卡恢復至原先狀態, 下次開機時將重複相同動作.

## 所面臨安裝套件問題

由於某些課程所使用的套件仍需 Windows 7, 因此在八樓電腦輔助設計室仍保留第一磁區規劃安裝 Windows 7 64 位元操作系統, 而第二磁區則因為其他大部分課程需求, 安裝許多 CAD/CAE/CAM 以及各式軟硬體整合的商用套件, 在目前沒有整體規劃配置的情況下, 16 GB的記憶體仍無法讓開機後的執行順暢, 因此第二磁區目前所面臨的問題, 除了操作系統反覆更新的問題之外, 還牽涉如何有效配置所安裝的軟體, 讓使用者啟用任一套件時, 能夠順暢運行.

電腦輔助設計室第三磁區雖然僅安裝 Windows 操作系統與可攜套件, 但是使用數個免費的軟體套件, 因此除了 Windows 10 反覆更新問題之外, 必須確認這些免費封閉套件並未對系統造成危害, 拖累操作速度.

另外, 在第三磁區曾經試圖開啟保護模式, 令其 Windows 10 更新, 但可能因為硬體或設定問題, 無法順利完成操作系統更新, 甚至導致無法開機進退兩難的情況.

# 目前開機速度

電腦輔助設計室第三磁區, 從開機到操作系統接受滑鼠點擊反應, 約需時 15 分鐘, 關機時重複進行操作系統更新.

# 預計處理模式

電腦輔助設計室第一與第二磁區, 目前除了優先改善操作系統問題外, 無其他套件改善方案.

至於第三磁區, 則希望撤銷保護模式, 僅安裝 Windows 10, 並試圖導入 Windows Server 2016 標準版本, 在協同產品設計實習室中的六台電腦測試, 是否可以利用 Windows 的管理方案, 在無防寫卡的情況下, 先解決第三磁區的問題, 然後再處理第一與第二磁區的規劃與軟體安裝問題.

#  TCPIP 網路連線設定問題

電腦教室目前仍利用 NAT, 以 IPv4 設定為主, 部分工作站伺服器則支援 IPv4 與 IPv6 雙支援代理主機功能, 但其他電腦則並未採較多網址的 IPv6 模式設定, 因此在上課期間, 全系超過兩百台電腦連線的情況下, 八樓兩間電腦教室中的 120 台電腦僅依賴兩個 IPv4 網址對外連線, 造成網路速度不佳, 雖然透過工作站室中的雙支援代理主機群接應, 仍僅達堪用情況, 並未充分運用聯外的 1 GB 網路頻寬.

# 參考資料

[部署 AutoDesk 套件到多台電腦](https://knowledge.autodesk.com/search-result/caas/sfdcarticles/sfdcarticles/Deploying-Autodesk-Software-to-Many-Computers.html)

## 需求
  .  網路共享區與客戶電腦硬碟必須有足夠空間
  .  網路共享區必須執行 Windows Server 操作系統, 能夠同時支援多部電腦連線 
  .  支援 TCP/IP 協定網路

MS Windows 參考:

https://docs.microsoft.com/zh-tw/windows/deployment/windows-deployment-scenarios-and-tools
https://docs.microsoft.com/zh-tw/windows/deployment/configure-a-pxe-server-to-load-windows-pe

[Windows server 比較](https://www.microsoft.com/zh-tw/cloud-platform/windows-server-comparison

https://github.com/veyon/veyon/)

內建於 Windows server 2016 中的 [multipoint service](http://www.netadmin.com.tw/article_content.aspx?sn=1703300002)

# 遠端透過 Proxy 啟用 Windows 授權

  *  先設定 IE 透過 Proxy Server 連線至系區網
  *  設定 Windows System-Wide Proxy
  *  修改防火牆讓 Windows Management Instrumentation 服務可以通過防火牆
  *  執行 KMS 認證

##  Windows Set System-Wide Proxy

    netsh winhttp import proxy source=ie

[nfu_ssl_vpn.pdf](https://github.com/mdecourse/wcms2018/files/1958367/nfu_ssl_vpn.pdf)

**Comment by jmscsl** [comment]
各位老師大家好：

一、謝謝嚴老師的說明及建立溝通平台。

 

二、若移除防寫卡，

 

甲、同學若不小心誤刪軟體，造成軟體無法開啟，將立即影響上課。

乙、還有頑皮學生在桌面上貼養眼圖片，造成不必要困擾，都是要考慮的因素。

丙、老師機樣本軟體安裝完成後，如何複製到學生電腦5～60台電腦，將是費時費力的工程。

丁、目前利用防寫卡網路功能複製發射給學生電腦硬碟，尚需三天三夜，若由人力一台一台複製硬碟，將是大工程。

 

三、敬請大家多表達看法，以達集思廣益之效。

**Comment by jmscsl** [comment]
各位老師大家好：

一、謝謝嚴老師的說明及建立溝通平台。

二、若移除防寫卡，

甲、同學若不小心誤刪軟體，造成軟體無法開啟，將立即影響上課。

乙、還有頑皮學生在桌面上貼養眼圖片，造成不必要困擾，都是要考慮的因素。

丙、老師機樣本軟體安裝完成後，如何複製到學生電腦5～60台電腦，將是費時費力的工程。

丁、目前利用防寫卡網路功能複製發射給學生電腦硬碟，尚需三天三夜，而且還昨不是百分之百成功，有時還需要第二、三次發射，才能整間教室完工。若由人力一台一台複製硬碟，將是大工程。

三、敬請大家多表達看法，以達集思廣益之效。

**Comment by jmscsl** [comment]
各位老師大家好：

一、謝謝嚴老師的說明及建立溝通平台。

二、若移除防寫卡，

甲、同學若不小心誤刪軟體，造成軟體無法開啟，將立即影響上課。

乙、還有頑皮學生在桌面上貼養眼圖片，造成不必要困擾，都是要考慮的因素。

丙、老師機樣本軟體安裝完成後，如何複製到學生電腦5～60台電腦，將是費時費力的工程。

丁、目前利用防寫卡網路功能複製發射給學生電腦硬碟，尚需三天三夜，而且還不是百分之百成功，有時還需要第二、三次發射，才能整間教室完工。若由人力一台一台複製硬碟，將是大工程。

三、敬請大家多表達看法，以達集思廣益之效。

**Comment by mdecourse** [comment]
# 群準參考資料

[evo_ref1.pdf](https://github.com/mdecourse/wcms2018/files/1941714/evo_ref1.pdf)

**Comment by mdecourse** [comment]
# CD1 電腦測試

重新在群準 EVO UEFI V8 還原卡模式下, 規劃三個磁區, 前兩個為 Windows 10 NTFS, 第三個為 ext 準備安裝 Ubuntu 18.04

結果: 

Windows 10 磁區只安裝 Chrome 與 Firefox 時, 從啟動到出現桌面約需 40 秒

分割為 ext 的磁區目前無法安裝 Ubuntu 18.04 beta 2 操作系統 - 原因待查

其他:

利用  EVO 功能, 將第一磁區資料複製到第二個 Windows 10 NTFS 磁區

**Comment by jmscsl** [comment]
Tks

 

 

＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊
國立虎尾科技大學　機械設計工程系
詹明樹　敬上
(63201)雲林縣西安里虎尾鎮文化路64號
TEL: (05)6315360,  0908-829270(4G台灣之星)
FAX: (05)6363010；0939-258843(3G台灣大哥大)
E-mail： <mailto:jms@nfu.edu.tw> jms@nfu.edu.tw ；Line:jmscsl

＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊

 

  _____

**Comment by mdecourse** [comment]
# Windows 10  安裝容量統計

根據 https://www.microsoft.com/zh-tw/windows/windows-10-specifications 安裝 Windows 10 專業版操作系統, 約需 20 GB 硬碟容量

根據 https://products.office.com/zh-tw/office-system-requirements 安裝 MS Office 2016 專業版約需 3 GB 硬碟, 取 5GB

# 計算機程式、網際內容管理、電腦輔助設計實習與協同產品設計實習

可攜工具佔硬碟容量為 20 GB + 完整安裝 PTC Creo 5.0 約需 10 GB 硬碟容量

# 最小硬碟分割

Windows 10 (20 GB) + MS Office (5 GB) + 可攜工具 (20 GB) + Creo (10 GB) + 45 G 工作空間 = 100 GB

選擇 100 GB 為電腦輔助設計室最小開機硬碟分割

# AutoCAD 2018 硬碟需求

根據 [System-requirements-for-AutoCAD](https://knowledge.autodesk.com/zh-hans/support/autocad/learn-explore/caas/sfdcarticles/sfdcarticles/CHS/System-requirements-for-AutoCAD-2018.html) 約需 5 GB 硬碟容量

# Solidworks 2018

根據 [solidworks-2018-hardware-recommendations](https://www.javelin-tech.com/blog/2017/11/solidworks-2018-hardware-recommendations/) 約需 20 GB 硬碟容量

# AutoDesk Inventor 

根據 [Inventor 2017 Specification](https://knowledge.autodesk.com/support/inventor-products/learn-explore/caas/sfdcarticles/sfdcarticles/System-requirements-for-Autodesk-Inventor-2017-products.html ) 完整安裝 Inventor 約需 40 GB 硬碟容量

# PTC Creo 5.0

完整安裝 PTC Creo 5.0 約需 10 GB 硬碟容量

# Matlab 2018

根據 https://ww2.mathworks.cn/en/support/sysreq.html Matlab 完整安裝約需 25 GB 硬碟容量

# Mathematica 11

根據 http://www.wolfram.com/mathematica/system-requirements.html Mathematica 安裝約需 15 GB 硬碟容量

# Labview

根據 http://www.ni.com/white-paper/53740/en/ Labview 完整安裝約需 35 GB 硬碟容量

# Ansys

根據 https://www.quora.com/What-are-the-minimum-requirements-for-ANSYS 建議, 大型專案執行約需 120 GB 硬碟容量

# Comsol

根據 https://www.comsol.com/system-requirements, Comsol 安裝與執行約需 10 GB 硬碟容量

# 硬碟容量統計

最小硬碟規劃 - 100 GB

CAD 套件:

AutoCAD - 5 GB
Solidworks - 20 GB
Inventor - 40 GB
Creo - 10 GB

四套 CAD 全安裝, 需 75 GB 硬碟容量

CAE 套件:

Ansys - 120 GB
Comsol - 10 GB

兩套 CAE 全安裝, 需 130 GB 硬碟容量

Math 套件:

Matlab - 25 GB
Mathematica - 15 GB

兩套 Math 套件全安裝, 需 40 GB 硬碟容量

系統工程套件:

Labview - 35 GB

以上全部安裝:

操作系統 (20 GB) + Office (5 GB) + CAD (75 GB) + CAE (130 GB) + Math (40 GB) + Labview (35 GB) + 可攜套件 (20 GB) + 工作空間 (55 GB) = 380 GB

最小安裝:

Windows 10 (20 GB) + MS Office (5 GB) + 可攜工具 (20 GB) + Creo (10 GB) + 45 G 工作空間 = 100 GB

# 初步結論

群準還原卡磁區規劃 - 2 TB 硬碟, 分割為 8 區, 類型均為 A, 100 GB 四區, 300 GB 兩區, 500 GB 兩區

100 GB 磁區 (base) - 安裝 Win 10 (20 GB) + Office (5 GB) + 可攜套件 (20 GB) + Creo (10 GB)
100 GB 磁區 (base2)- 分割後隱藏備用, 或安裝套件與 base 相同, 但操作系統使用 Win 7
100 GB 磁區 (acad)- 安裝 Win 10 (20 GB) + Office (5 GB) + AutoCAD (5 GB)
100 GB 磁區 (acad2) - 分割後隱藏備用, 或安裝套件與 acad2 相同, 但操作系統使用 Win 7
300 GB 磁區 (cax) - 安裝 Win 10 (20 GB) + Office (5 GB) + Solidworks (20 GB) + CAE (130 GB) + Math (40 GB) 
300 GB 磁區 (cax2)  - 分割後隱藏備用, 或安裝套件與 cax 相同, 但操作系統使用 Win 7
500 GB 磁區 (all) - 安裝 Win 10 (20 GB) + Office (5 GB) + CAD (75 GB) + CAE (130 GB) + Math (40 GB) + Labview (35 GB) + 可攜套件 (20 GB) 
500 GB 磁區 (all2) - 分割後隱藏備用, 或安裝套件與 cax 相同, 但操作系統使用 Win 7

**Comment by mdecourse** [comment]
# 計算機程式、網際內容管理、電腦輔助設計與協同產品設計實習

可攜程式系統所安裝的內容如下:

d3dcompiler_43.dll (配合 solvespace.exe 執行)
fossil.exe (fossil scm 執行程式)
launchLeo.py (啟動 Leo Editor 原始碼)
libwinpthread-1.dll (配合 solvespace.exe 執行)
Readme.txt (Readme 文件檔)
solvespace.exe (Solvespace 簡潔的 3D 參數設計繪圖程式)
Blender (數位模擬套件)
boost_1_66_0 (C++ 程式庫)
cmake-3.10.1-win64-x64 (CMake)
coreutils-5.3.0 (編譯 Fossil SCM 時使用)
depends22_x64 (檢查程式執行所需連結程式庫)
diffutils-2.8.7-1 (檢查檔案差異工具)
FileZillaPortable (sftp 套件)
fossil (Fossil SCM 下載解開 working directory 所在目錄)
git (版次管理工具客戶端)
graphviz-2.38 (Pyslvs 開發所需) 
home (可攜環境用戶目錄)
jom_1_1_2 (Jom)
KDiff3 (檢查檔案差異工具)
LLVM (LLVM)
lua-5.3.4 (Lua 解譯程式套件)
LuaJIT-2.0.5 (JIT 版本 Lua 解譯程式套件)
miktex_portable (MikTeX 用於編譯 TeX 與 LaTeX 文件)
msys64 (Msys2 程式開發套件)
pandoc-2.0.2 (Pandoc 文件格式轉換工具)
patch-2.5.9-7 (Patch 工具)
processexplorer (Process Explorer 工具)
Python36 (Python 解譯程式套件)
qbs-windows-x86_64-1.10.0 (qbs)
QScintilla_gpl-2.10.2 (QScintilla)
scite (SciTE 文件編輯器)
solvespace (Solvespace 3D 參數設計繪圖軟體)
Strawberry (Strawberry Perl 解譯程式套件)
stunnel (Stunnel SSL proxy server)
swigwin-3.0.12 (SWIG)
tinycc (ANSI C 編譯器)
tmp (tmp 目錄)
vrep340_rev1 (V-rep 機器人模擬平台)
vrep_kmol (自行編譯的 V-rep)
Xming (Xming X server)
xsltproc (xsltproc)
ZoomIt (ZoomIt 放大螢幕工具)
luajit.exe (JIT lua)
lua51.dll (JIT lua 執行所需動態連結庫)
sharex_portable (電腦操作動畫錄製工具)
wget (Wget 工具)

**Comment by mdecourse** [comment]
# 協同設計室電腦安裝

本學期購入的六台電腦, 各分為六個磁區 (500GB x2, 300GBx2, 100GBx2) 已經初步安裝, 均透過群準 EVO UEFI V8 防寫卡保護, 每一磁區均安裝:

Windows 10 Prof 64 位元操作系統
MS Office 2016 Plus (Access, Word, Excel 與 PowerPoint)
7-zip

## CD1-CD5 測試機

安裝 EVO UEFI 防寫卡, 採 GPT 分割, all and all-1 500GB, cax and cax-1 300GB, base and base-1 100GB

## CD6 伺服主機

拆除防寫卡, 安裝 Windows 10 Prof 64 位元, Virtualbox, MS Office 2016 plus, 7zip

**Comment by mdecourse** [comment]
# 電腦輔助設計室現有磁區處理

## 第一 (Win 7) 與第二 (Win 10) 磁區

將目前的第一與第二磁區以 https://docs.microsoft.com/en-us/sysinternals/downloads/disk2vhd 轉為 vhd, 然後利用 Virutlabox 開機, 測試能否以虛擬機格式保留並調適現有已經安裝的程式.


## 第三 (Win 10) 磁區

已經重新安裝系統, 以及 Office 2016 plus 及 7zip, 準備利用 Clonezilla 將此新安裝磁區複製到第三磁區

製作流程, 以 http://tuxboot.nchc.org.tw 製作 Clonezilla 開機 USB 隨身碟, 開機後, 將新安裝
第三磁區轉為 image 檔案 ,然後以 image restore 方式轉到舊電腦的第三磁區.

**Comment by mdecourse** [comment]
# 門禁與智能管理

[RC522 RFID](http://www.playrobot.com/rfid/139-13-56-rfid-mifare-nfc.html)

[RC522 RFID2](http://goods.ruten.com.tw/item/show?21512663552783) ([ref](https://blog.csdn.net/Leytton/article/details/73480974))

[參考資料](https://sites.google.com/a/nsysu.kksh.kh.edu.tw/tg02-1/the-germs-of-maker-on-campus)

[Arduino + RC522 RFID](http://goods.ruten.com.tw/item/show?21211178347041)

**Comment by mdecourse** [comment]
# W14 週總結報告

## 0810-1609 批次電腦

電腦輔助設計室在 2016 年 9 月所更新的電腦將以該室的代號 0810 加上採購時間 1609 稱呼, 意即該批電腦的維護與管理批號設為: 0810-1609, 共採購 63 (教室) + 1 (教師) + 2 (伺服器) = 66 台, [0810-1609 硬體規格](http://project.mde.tw/blog/yen-dian-nao-fu-zhu-she-ji-shi-dian-nao-pei-zhi.html).

0810-1609 批次電腦雖然使用 UEFI BIOS, 但是因為搭配的群準還原卡為 Pro V6 版本, 只能支援 MBR 的硬碟分割, 但已經足夠用來分割原始配備的 2TB 硬碟. 

## 0811-1804 批次電腦

至於協同設計室中的六台 0811-1804 電腦在規格上與 0810-1609 相似, 但是配置的群準還原卡為 UEFI V8 版本, 只支援 GPT 硬碟分割, 因此在後續的硬碟複製與部署格式及操作方法均有所不同.

## 協同設計室周邊

協同設計室目前已經加裝保全不鏽鋼門以及門禁刷卡及內外錄影存證系統, 因此透過設定, 可以允許相關課程學生自由進出使用所配置的所有軟硬體.

# 電腦輔助設計室 0810-1609 電腦規劃

## 0810-1609 第二磁區

截至 2018.05.28, 負責維護廠商已經成功將第二磁區中的 Windows 10 更新為 1804 版本, 且關閉自動更新設定, 並將群準還原卡中的操作系統版本保護暫存區清除, 因此已經改善先前開機後重複下載並更新 Windows 10 1604 與 1709 版本的問題 (目前從校方下載的 Windows 10 安裝 iso 為 2015 年版本, 建議不要再使用此一版本, 而可從 https://www.microsoft.com/zh-tw/software-download/windows10 下載最新版本)

## 0810-1609 第一磁區

由於部分工具機的控制器至今仍只支援 Windows 7, 因此電腦輔助設計室中的第一磁區仍予保留, 但已不再更新維護, 只保留原始 2016.09 所製作的版本.

## 0810-1609 第三磁區

此一磁區將只安裝 Windows 10 pro 64 位元版本, MS Office plus 2016 版本, 7zip 與 Firefox, 其餘配合此一磁區使用的程式建議製作成可攜套件, 讓使用者從 USB 硬碟或隨身碟取用, 也可在不安裝的情況下複製到硬碟中備用.

建議此一磁區除上述基本套件外, 不要再安裝 teamviewer 或其他必須經由 Windows 10 系統安裝的套件.

0810-1609 第三磁區預計在 W15 週完成安裝後, 0810-1609-64 與 0810-1609-65 電腦將保留一份原始規劃版本與一份測試版本開放讓所有師生進行測試.

# 0810-1609 新版本複製部署

2018.07.10 之後應可進行 0810-1609 新版本的複製部署

**Comment by mdecourse** [comment]
# 電腦輔助設計室第二磁區 on Virtualbox 測試

Matlab R2017a on IPv4 連線:

![matlab_r2017a_on_vb](https://user-images.githubusercontent.com/20835445/40708043-f90e6b38-6424-11e8-80a3-b41a7b94054b.png)

Ansys 18.1 Workbench on IPv4 連線:

![ansys_18 1_workbench](https://user-images.githubusercontent.com/20835445/40708316-c274fb9a-6425-11e8-94ca-bd88feab2c88.png)

Mathematica 9 on IPv4 連線:

![mathematica9](https://user-images.githubusercontent.com/20835445/40708494-2b5c397a-6426-11e8-8be5-e004baf4782a.png)

Moldex3D R15 on IPv4 連線:

![moldex3d_r15](https://user-images.githubusercontent.com/20835445/40708779-e716b2f8-6426-11e8-9f74-b66be174ac60.png)

AutoDesk A360 on IPv4 連線:

![autodesk_a360](https://user-images.githubusercontent.com/20835445/40709265-2f8bf8c6-6428-11e8-9266-8f0733747cc4.png)

PTC Creo Parametric 3 M090 on IPv4 連線:

![ptc_creo3_m090](https://user-images.githubusercontent.com/20835445/40709688-5247e7a2-6429-11e8-88b9-3fa4e8823c0d.png)

AutoCAD 2016 on IPv4 連線:

![autocad_2016](https://user-images.githubusercontent.com/20835445/40710490-5d8d9f60-642b-11e8-83f1-63c5e5db609a.png)

Abaqus CAE on IPv4 連線:

![abaqus_cae](https://user-images.githubusercontent.com/20835445/40708803-f64c6966-6426-11e8-848e-5c620bed2a13.png)

RecurDyn V8R5 on IPv4 連線:

![recurdyn_v8r5](https://user-images.githubusercontent.com/20835445/40709514-d5e75918-6428-11e8-847c-6d1d39f61316.png)

**Comment by mdecourse** [comment]
https://www.cnet.com/how-to/easy-ways-to-speed-up-windows-10/

https://fossbytes.com/speed-up-windows-performance-tips/

**Comment by mdecourse** [comment]
# 2018 Fall CADLab 群準複製
將來源主機的還原卡程式改回 2016.07.26 版本, 以 16 位元模式複製, 完成後, 若 client 端網卡鬆脫, 則會出現無法啟動網卡驅動程式 (因 V6 版本還原卡無法自動搜尋所驅動的網卡), 而出現黑畫面, 等待重新開機並插緊網卡插槽.

若 client 端出現 mbr 丟失無法開機, 則必須重新複製.

若先前已經採 32 位元模式複製之電腦, 經由舊版 16 位元模式複製後, 將出現無法自行重設 IP 的警告, 可能要手動修復.

# 結論

一直以來採用群準 V6 mbr 規劃下的還原卡管理, 是以舊版 2016.07.26 驅動程式執行 16 位元, 配合 No17 網卡 (瑞昱) 複製, 資料傳輸速度僅約 600MB/分, 與 32 位元,  配合 No11  網卡 (主機板上方 Intel 網卡) 可取得的 6500MB/分, 差 10 倍之多.

惟因採 32 位元 + No11 網卡設定複製後, 無法如 16 位元複製後, 資料還原組合無需重新開機整合 (每磁區需於複製後, 重新在內定開放模式下開機各一次, 才能完成資料還原設定). 因此往後的管理複製需要進一步確認各模式的實用情況後, 設法改進.

**Comment by mdecourse** [comment]
# 2018 Fall 規劃電腦輔助繪圖室電腦還原系統

目前擬採用的系統為 [EVO Cloud 雲端管理系統](http://www.teamsoftex.com/tw/goods.php?act=view&no=20)

![p37_19-54-39](https://user-images.githubusercontent.com/20835445/47603693-6438fe00-da22-11e8-9790-93747741cb25.png)

產品型錄: [Cloud.pdf](https://github.com/mdecourse/wcms2018/files/2521726/Cloud.pdf)

# 產品功能:

## 創新的硬碟快取技術

EVO Cloud 具備了硬碟快取技術，大幅降低對網路的依賴度，使用者電腦第一次連接伺服器開啟系統將快取資料寫入至使用者硬碟中後，此電腦重新開機快取資料依然存在於本機硬碟中，因此用戶端不必一再向伺服器索取相同的快取資料，大幅降低伺服器資料存取及網路流量的壓力。

此外，為配合使用者端原始硬碟規劃，EVO Cloud 推出了創新的硬碟快取技術，硬碟快取區域可規劃配置作業系統於任何一個磁碟分割區中，大大提升了部屬新環境的速度。

## 全新的遠端控制技術

除了管理使用者系統外，EVO Cloud 更具備了遠端維護電腦的功能，維護電腦不再需要親自到每一台電腦前面，透過我們的遠端維護功能，可即時操作使用者電腦，再遠的距離也無須擔心，而且配合節點精靈功能，更新系統一指搞定。

## 具備離線開機功能

我們都知道無硬碟系統以及虛擬化架構系統最大的災難來自於伺服器無預警毀損、停擺，造成用戶端無法預期的損害，而 EVO Cloud 具備了離線快取技術，使用者在初次開啟系統後，資料將寫入至使用者硬碟中，當快取資料寫入進度達100%後，此用戶端就可以在完全不連接伺服器的情況下，使用已經開過的節點開機進入系統。

# 建議

希望在決定是否採用此系統之前, 讓系上使用者實際了解此系統的所有功能, 並與類似產品進行比較.

**Comment by mdecourse** [comment]
# mde DNS 伺服器
採 Virtualbox Ubuntu 18.04.1, 以 BIND9 建立 dns, dns2, 虛擬主機循 Open Virtualization Format 2.0 規格 export 燒製 Blue Ray 光碟片中備用.

# 電腦輔助繪圖室 0830-1307 電腦

0830-1307 表示該批電腦為 2013 年 07 月購入, 置於編號 0830 實驗室.

為 i5 有 vt 支援, 每台有 4GB 記憶體, 若兩台組成一台, 可用來建立 Proxy 與 Web based Servers.

**Comment by mdecourse** [comment]
# 網卡 MAC 00-e0-98-29-9c-70 的 DHCP server 錯誤設定

可能硬體:

Abocom 友旺 A38 四核心 4K2K 智慧電視盒

AboCom友旺具網路管理功能之交換器

AboCom 網路強波器

**Comment by mdecourse** [comment]
# 2019.11.13 電腦輔助設計室 IPv4 Router 網速檢測
發現連入 Router 後, 網速驟降, 懷疑可能設定問題或 Router 中的 log 未清除造成.
必須找時間登入後確認實際問題.

# 目前 cp2019 與 cad2019 上課模式
直接使用 IPv6 連線, 並透過 IPv4 與 IPv6 雙支援代理主機讓 60 名使用者利用 Github 倉儲上課.

在純 IPv6 連線下, 以 SSH 對 Github push 的相關設定與用法:

https://github.com/mdecourse/cad2019/issues/20

而讓使用者可以透過 GitExtension 與 Git GUI 工具, 較方便輸入中文提交訊息的[說明](http://mde.tw/cad2019/content/%E5%B0%8E%E5%85%A5%20GitExtensions.html):

**Comment by mdecourse** [comment]
# 主機 2, 3, 4

OpenSSH 7.6p1 未限制可連線 IP
nginx 1.14.0 已經漏洞版本

# 32, 42, 53, 69

OpenSSH  8.2p1 未限制可連線 IP
nginx 1.17.10

**Comment by mdecourse** [comment]
# 代理主機被鎖卡議題
2021-04-16 09:04:37 69 被判定有以下網路侵害問題:

疑似對外進行非法的入侵攻擊，透過每10秒約50次的ssh連線需求，並猜測密碼來進行暴力破解攻擊，攻擊成功後可利用使用者權限來安裝程式或瀏覽、變更、刪除資料，或是拖垮伺服器網路流量及效能來達成阻斷式服務攻擊。 影響範圍：所有使用SSH的伺服器。

# 處理方式

先將原先提供 downloads 檔案移出到 17
