### ISSUE TITLE
wcms-week 春假

### ISSUE THREAD

**Issue by mdecourse** [mdecourse/wcms2018#8]
請各組將課程至今的心得寫在以下 issues 中.

**Comment by 40623128** [comment]
第十組心得:
上課至今我學到了很多，像如何查詢自己的IP位址、使用虛擬主機與個人電腦連線、自動填入資料的組態等等，很多東西我以前有聽過，但是都沒有接觸，上這門課讓我有機會接觸，還有利用Heroku配合Flask、Python、css等架設個人網頁，目前我覺得最便利的非組態莫屬，點兩下就自動設好proxy了，真的省了很多時間，而且這學期上課比上學期有趣多了，因為老師分享了很多有趣的實例，像學校雲端點名沒超文字傳輸安全協定很危險容易被駭等，最後期待老師教我們做網路線。
總結:
有選這門課太好了，有學到新東西，期待日後的課程。

**Comment by 40623116** [comment]
第四組心得:
    剛接觸到這門課時，原以為又像上學期一樣，大家一起合力完成一份作業，但這學期學的東西讓我感覺對網路的認知又更加地深入一點，從小就對電腦沒興趣的我們，也開始慢慢地喜歡上這門課，想更加的努力學習，每次上課都很期待今天上課又能學到什麼我們不知道的東西，例如Python、Heroku、css等等，都讓我們大開眼界，彷彿重新認識網際網路的世界一般，也謝謝老師藉由很多生活上的例子，使大家加快理解，雖然我們還處於網路世界的井底之蛙，但藉由這門課我們也開始碰到一點網路世界精髓的邊了。
總結：
很高興當初沒有決定回家，反而選擇留下來上這門課，往後希望能學到更多的東西。

**Comment by 40623127** [comment]
第七組心得:
這學期老師讓我們接觸不同的電腦作業系統，雖然是使用virtualbox這個虛擬主機開啟它，讓我們了解原來除了Microsoft Windows之外還有其他好用的系統，讓我們太開眼界，期待期末時老師讓我們做網路線，讓不同主機可以互相連線，可以學到更多的知識。
總結:
還好有選這克選修讓，沒有讓我們星期五的下午白白浪費掉，也學到更多關於網際網路的知識。

**Comment by 40623105** [comment]
第十二組心得：
一開始選這門課，不懂這門課所要傳達的觀念是甚麼？第一堂課ＴＡ有撥放給我們一段影片，一開始也是迷迷糊糊的不知道要做甚麼，直到老師開始上課後，才漸漸了解了，網際網路這門課的意義。這門選修課學習到很多以前沒有使用過的東西，像是Heroku、虛擬主機、架設網站等等……每次的課程老師都會結合生活的例子，都讓我們覺得對網際網路又更熟悉了一些。
總結：
覺得這學期的課程是比較貼近生活的，希望以後可以學習更多實用的網際網路課程。

**Comment by 40623121** [comment]
第十五組心得:
自從一上修了尊師的課之後深深的覺得網路的知識海洋比我想像中寬廣，觸及和可用的地方也很多，雖然一開始也是各種問號，想問組員意見結果都倒一片，從一開始的用cmd查詢自己的IP、使用virtualBox虛擬主機，自動設定proxy，省了很多步驟，雖然上學期比降好玩畢竟是網誌，
總結:
老師好年輕

**Comment by 40623118** [comment]
第八組心得 :
上這門課之後，與上學期所上的課有些不同，學會查自己所在的IP位置，利用Python、Heroku、css等等來架設網頁，也利用virtualbox 虛擬主機來測試自己想要開發的東西，這些新的工具就像老師所說的，或許以後沒有人會願意幫我們整理或教我們。雖然要全部了解這些概念算是一個大挑戰，但我們會盡力去做的。
總結 :
學到更多關於網際網路的知識，也了解到部分網頁是有被駭的機率，例如學校的雲端點名統。

**Comment by 40623150** [comment]
第三組心得:
這門課每堂課程都在接收著全新東西，跟上學期一樣，一開始或許聽不是很懂，但經過老師的影片還有同學幫助後，漸漸了解Heroku、虛擬主機、架設網站之類的，也了解到知識並不只存在於書本上，網路的世界才能提供我們源源不絕的知識，只有用網路才能不斷更新自己的見聞。

**Comment by 40623140** [comment]
第十四組：
40623140 韓希然
進一步了解github的前提下對heroku 倉儲進行了初步的理解
學習了Heroku 倉儲的管理，虛擬主機的架構，和個人網站的安排
對網際內容管理這門課有了比較深入的了解。
老師也叫教會了我們很多對網絡架構的概念。
未來的世界是互聯網和物聯網的世界，在老師的教導下我會認真學習網絡知識，做一名合格的機械設計者。
